-- ============================================
-- TCT SCROOPER - PROPERTY INDEX SCHEMA v2
-- PostgreSQL (Supabase)
-- ============================================

-- ============================================
-- CORE
-- ============================================

CREATE TABLE properties (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	fingerprint TEXT UNIQUE NOT NULL,
	country TEXT DEFAULT 'CA',
	province TEXT,
	city TEXT,
	postal_code TEXT,
	address_full TEXT,
	lat REAL,
	lng REAL,
	unit_number TEXT,
	floor INTEGER DEFAULT 1,
	stories INTEGER DEFAULT 1,
	-- property_type: condo, house, townhouse, duplex, semi_detached, detached, land
	property_type TEXT,
	year_built INTEGER,
	lot_sqft INTEGER,
	beds INTEGER,
	baths INTEGER,
	sqft INTEGER,
	details JSONB,
	created_at TIMESTAMPTZ DEFAULT NOW(),
	updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE property_identifiers (
	property_id UUID NOT NULL REFERENCES properties(id),
	-- type: mls, internal, parcel, tax_roll
	type TEXT NOT NULL,
	identifier TEXT NOT NULL,
	source TEXT,
	PRIMARY KEY (property_id, type, identifier)
);

CREATE TABLE listings (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	property_id UUID NOT NULL REFERENCES properties(id),
	-- source: realtor_ca, zillow, centris, housesigma, craigslist
	source TEXT NOT NULL,
	external_id TEXT,
	url TEXT,
	-- type: sale, rent, sale_and_rent
	type TEXT NOT NULL,
	-- status: active, delisted, expired, withdrawn, pending, terminated
	status TEXT,
	price NUMERIC,
	currency TEXT DEFAULT 'CAD',
	fees JSONB, -- { "condo": 450, "condo_period": "monthly" }
	-- Listing-snapshot of property attributes (may differ from properties table)
	-- property_type: condo, house, townhouse, duplex, semi_detached, detached, land
	property_type TEXT,
	beds INTEGER,
	baths INTEGER,
	sqft INTEGER,
	sqft_lot INTEGER,
	floor INTEGER DEFAULT 1,
	stories INTEGER DEFAULT 1,
	description TEXT,
	features JSONB, -- ['pool', 'garage', 'fireplace', 'in_unit_laundry']
	raw_data JSONB,
	last_seen TIMESTAMPTZ DEFAULT NOW(),
	listed_at TIMESTAMPTZ DEFAULT NOW(),
	delisted_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ DEFAULT NOW(),
	updated_at TIMESTAMPTZ DEFAULT NOW(),
	UNIQUE(source, external_id)
);

-- ============================================
-- MARKET PARTICIPANTS
-- ============================================

CREATE TABLE media (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	s3_key TEXT UNIQUE,
	content_hash TEXT,
	-- media_type: image, video, document
	media_type TEXT DEFAULT 'image',
	mime_type TEXT,
	file_size_bytes BIGINT,
	original_url TEXT,
	height INTEGER,
	width INTEGER,
	pages INTEGER,
	duration INTEGER,
	-- status: pending, processing, uploaded, failed
	status TEXT DEFAULT 'pending',
	-- attempts: number of media worker tries
	attempts INTEGER DEFAULT 0,
	metadata JSONB,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE brokerages (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name TEXT NOT NULL,
	-- brand: RE/MAX, Century 21, Royal LePage, Keller Williams, Coldwell Banker
	brand TEXT,
	phone TEXT,
	email TEXT,
	website TEXT,
	address TEXT,
	country TEXT,
	city TEXT,
	province TEXT,
	logo_id UUID REFERENCES media(id),
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE agents (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	full_name TEXT NOT NULL,
	license_number TEXT,
	email TEXT,
	phone TEXT,
	bio TEXT,
	brokerage_id UUID REFERENCES brokerages(id),
	headshot_id UUID REFERENCES media(id),
	first_seen_at TIMESTAMPTZ DEFAULT NOW(),
	last_seen_at TIMESTAMPTZ DEFAULT NOW(),
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE listing_agents (
	listing_id UUID NOT NULL REFERENCES listings(id),
	agent_id UUID NOT NULL REFERENCES agents(id),
	-- role: listing, buying, co_listing, referral
	role TEXT NOT NULL,
	PRIMARY KEY (listing_id, agent_id)
);

-- ============================================
-- MEDIA BRIDGES
-- ============================================

CREATE TABLE listing_media (
	listing_id UUID NOT NULL REFERENCES listings(id),
	media_id UUID NOT NULL REFERENCES media(id),
	position INTEGER,
	PRIMARY KEY (listing_id, media_id)
);

-- ============================================
-- DEDUPLICATION
-- ============================================

CREATE TABLE property_matches (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	matched_id UUID NOT NULL REFERENCES properties(id),
	incoming_id UUID NOT NULL REFERENCES properties(id),
	confidence REAL,
	match_reasons JSONB, -- ['same_address', 'same_coords', 'similar_sqft', 'same_mls', 'fuzzy_address']
	-- status: pending, confirmed, rejected
	status TEXT DEFAULT 'pending',
	reviewed_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ DEFAULT NOW(),
	UNIQUE(matched_id, incoming_id)
);

-- ============================================
-- TIMELINE & PRICES
-- ============================================

CREATE TABLE property_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	property_id UUID NOT NULL REFERENCES properties(id),
	-- event_type: listed, delisted, relisted, price_change,
	--   expired, pending, withdrawn, assessment, permit_issued,
	--   permit_completed, inspection, complaint, attribute_change
	event_type TEXT NOT NULL,
	event_date TIMESTAMPTZ NOT NULL,
	price NUMERIC,
	previous_price NUMERIC,
	summary TEXT,
	-- source_type: listing, assessment, record, intel, geo_event
	source_type TEXT,
	-- source: scraper, gov_import, manual, news_scraper, api
	source TEXT,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE price_points (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	property_id UUID NOT NULL REFERENCES properties(id),
	listing_id UUID REFERENCES listings(id),
	-- price_type: asking_sale, asking_rent, assessed_land,
	--   assessed_building, assessed_total, tax_annual,
	--   condo_fee, hoa_fee, mortgage_payment
	price_type TEXT NOT NULL,
	amount NUMERIC NOT NULL,
	currency TEXT DEFAULT 'CAD',
	-- period: one_time, monthly, yearly, bi_weekly
	period TEXT,
	effective_at TIMESTAMPTZ NOT NULL,
	-- source: scraper, gov_import, manual, bank
	source TEXT,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- PUBLIC RECORDS & INTEL
-- ============================================

CREATE TABLE property_assessments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	property_id UUID NOT NULL REFERENCES properties(id),
	-- assessment_type: scheduled, reassessment, appeal, transfer, municipal_revaluation
	assessment_type TEXT,
	assessed_value_land NUMERIC,
	assessed_value_building NUMERIC,
	assessed_value_total NUMERIC,
	tax_amount NUMERIC,
	-- property_class: residential, commercial, farm, mixed_use, industrial, exempt
	property_class TEXT,
	tax_rate REAL,
	effective_at TIMESTAMPTZ NOT NULL,
	-- source: mpac, city_portal, county_records, foia_request, manual
	source TEXT,
	source_url TEXT,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE property_records (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	property_id UUID NOT NULL REFERENCES properties(id),
	-- record_type: permit_building, permit_electrical, permit_plumbing,
	--   permit_demolition, permit_mechanical, permit_fire,
	--   inspection_home, inspection_termite, inspection_radon,
	--   inspection_fire, inspection_structural,
	--   survey_plot, survey_boundary, status_certificate,
	--   title_search, title_insurance, insurance_claim,
	--   zoning_decision, zoning_variance, hoa_minutes,
	--   condo_bylaws, environmental_assessment
	record_type TEXT NOT NULL,
	-- status: applied, under_review, approved, denied,
	--   in_progress, completed, expired, appealed, withdrawn
	status TEXT,
	reference_number TEXT,
	title TEXT,
	description TEXT,
	details JSONB, -- Permit: { "estimated_cost": 80000, "contractor": "..." }
	               -- Inspection: { "pass": true, "deficiencies": [...] }
	               -- Insurance: { "claim_amount": 15000, "cause": "water_damage" }
	media_id UUID REFERENCES media(id),
	-- source: city_portal, county_records, manual_upload,
	--   foia_request, realtor_provided, owner_provided
	source TEXT,
	source_url TEXT,
	issued_at TIMESTAMPTZ,
	expires_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE property_intel (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	property_id UUID NOT NULL REFERENCES properties(id),
	-- intel_type: noise_complaint, bylaw_violation, illegal_airbnb,
	--   grow_op_suspected, news_mention, court_filing,
	--   heritage_designation, condemned, fire_damage,
	--   tenant_dispute, foreclosure
	intel_type TEXT NOT NULL,
	title TEXT,
	description TEXT,
	-- credibility: verified, official, unconfirmed, rumor, retracted
	credibility TEXT,
	details JSONB,
	-- source: city_records, court_records, news_outlet,
	--   social_media, neighbor_report, manual
	source TEXT,
	source_url TEXT,
	occurred_at TIMESTAMPTZ,
	discovered_at TIMESTAMPTZ DEFAULT NOW(),
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE geo_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	-- event_type: chemical_spill, flood, wildfire, earthquake, tornado,
	--   rezoning, transit_expansion, school_closure, school_opening,
	--   landfill_approved, highway_construction, condo_development, power_plant
	event_type TEXT NOT NULL,
	title TEXT,
	description TEXT,
	lat REAL NOT NULL,
	lng REAL NOT NULL,
	affected_radius_km REAL,
	boundary JSONB,
	-- severity: info, advisory, warning, critical
	severity TEXT,
	details JSONB,
	-- source: city_records, news_outlet, environment_canada,
	--   usgs, transit_authority, manual
	source TEXT,
	source_url TEXT,
	occurred_at TIMESTAMPTZ,
	resolved_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- LINKS
-- ============================================

CREATE TABLE property_links (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	property_id UUID NOT NULL REFERENCES properties(id),
	listing_id UUID REFERENCES listings(id),
	url TEXT UNIQUE NOT NULL,
	-- site: realtor_ca, zillow, craigslist, kijiji, facebook, brokerage_site
	site TEXT NOT NULL,
	-- link_type: listing, fsbo, mention, suspicious
	link_type TEXT,
	is_primary BOOLEAN DEFAULT FALSE,
	is_active BOOLEAN DEFAULT TRUE,
	first_seen_at TIMESTAMPTZ DEFAULT NOW(),
	last_seen_at TIMESTAMPTZ DEFAULT NOW(),
	notes TEXT
);

-- ============================================
-- OPERATIONAL
-- ============================================

CREATE TABLE scrape_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	source TEXT,
	started_at TIMESTAMPTZ DEFAULT NOW(),
	finished_at TIMESTAMPTZ,
	-- status: running, completed, failed, partial, cancelled
	status TEXT,
	listings_found INTEGER DEFAULT 0,
	listings_new INTEGER DEFAULT 0,
	properties_new INTEGER DEFAULT 0,
	errors_count INTEGER DEFAULT 0,
	error_message TEXT,
	metadata JSONB
);

CREATE TABLE scrape_logs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	run_id BIGINT REFERENCES scrape_runs(id),
	timestamp TIMESTAMPTZ DEFAULT NOW(),
	-- level: debug, info, warn, error, fatal
	level TEXT,
	message TEXT,
	source_id TEXT
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_properties_fingerprint ON properties(fingerprint);
CREATE INDEX idx_properties_city ON properties(city);
CREATE INDEX idx_properties_postal ON properties(postal_code);
CREATE INDEX idx_properties_location ON properties(lat, lng);

CREATE INDEX idx_identifiers_lookup ON property_identifiers(type, identifier);

CREATE INDEX idx_listings_property ON listings(property_id);
CREATE INDEX idx_listings_status ON listings(status);
CREATE INDEX idx_listings_type ON listings(type);
CREATE INDEX idx_listings_price ON listings(price) WHERE price IS NOT NULL;
CREATE UNIQUE INDEX idx_one_active_listing ON listings(property_id) WHERE status = 'active';

CREATE INDEX idx_media_hash ON media(content_hash);

CREATE INDEX idx_agents_brokerage ON agents(brokerage_id);
CREATE INDEX idx_agents_license ON agents(license_number);

CREATE INDEX idx_listing_agents_agent ON listing_agents(agent_id);

CREATE INDEX idx_listing_media_listing ON listing_media(listing_id);

CREATE INDEX idx_matches_status ON property_matches(status);
CREATE INDEX idx_matches_matched ON property_matches(matched_id);
CREATE INDEX idx_matches_incoming ON property_matches(incoming_id);

CREATE INDEX idx_events_property ON property_events(property_id, event_date);
CREATE INDEX idx_events_type ON property_events(event_type, event_date);
CREATE INDEX idx_events_price ON property_events(price) WHERE price IS NOT NULL;
CREATE INDEX idx_events_recent ON property_events(event_date DESC);

CREATE INDEX idx_prices_property ON price_points(property_id, price_type, effective_at);
CREATE INDEX idx_prices_type ON price_points(price_type, effective_at);
CREATE INDEX idx_prices_amount ON price_points(amount) WHERE price_type = 'asking_sale';

CREATE INDEX idx_assessments_property ON property_assessments(property_id, effective_at);

CREATE INDEX idx_records_property ON property_records(property_id);
CREATE INDEX idx_records_type ON property_records(record_type);
CREATE INDEX idx_records_status ON property_records(status);

CREATE INDEX idx_intel_property ON property_intel(property_id);
CREATE INDEX idx_intel_type ON property_intel(intel_type);

CREATE INDEX idx_geo_events_location ON geo_events(lat, lng);
CREATE INDEX idx_geo_events_type ON geo_events(event_type);
CREATE INDEX idx_geo_events_active ON geo_events(resolved_at) WHERE resolved_at IS NULL;

CREATE INDEX idx_links_property ON property_links(property_id);
CREATE INDEX idx_links_listing ON property_links(listing_id);
CREATE INDEX idx_links_site ON property_links(site);

CREATE INDEX idx_runs_status ON scrape_runs(status, started_at);
CREATE INDEX idx_logs_run ON scrape_logs(run_id, timestamp);

-- ============================================
-- CONSTRAINTS
-- ============================================

ALTER TABLE price_points ADD CONSTRAINT chk_positive_amount CHECK (amount >= 0);
ALTER TABLE listings ADD CONSTRAINT chk_positive_price CHECK (price >= 0);
